version: '3'
services:
  # PostgreSQL Database with PostGIS
  db:
    image: postgis/postgis:13-3.1
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # GeoServer
  geoserver:
    image: docker.osgeo.org/geoserver:2.23.1
    container_name: geoserver
    ports:
      - "8080:8080"
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
#rewrite incase you want to store the data in an attached EBS volume
volumes:
  postgres-data:
  geoserver-data: